kind: pipeline
name: build
type: kubernetes

resources:
  requests:
    memory: 128Mi

steps:
- name: build
  image: golang:1.18-alpine
  pull: always
  commands:
    - apk --no-cache add git curl tar
    - curl -sL https://github.com/bpineau/katafygio/archive/refs/tags/v0.8.3.tar.gz | tar xzf - --strip-components=1
    - CGO_ENABLED=0 go build -ldflags -s .

- name: image
  image: plugins/docker
  pull: always
  settings:
    repo: ghcr.io/rkojedzinszky/katafygio
    dockerfile: Dockerfile.pack
    registry: ghcr.io
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    auto_tag: true
    auto_label: false
    mirror:
      from_secret: hub_docker_mirror

  privileged: true
  volumes:
    - name: docker
      path: /var/lib/docker

volumes:
  - name: docker
    temp: {}
