FROM alpine:3.15

LABEL org.opencontainers.image.authors "Richard Kojedzinszky <richard@kojedz.in>"
LABEL org.opencontainers.image.source https://github.com/rkojedzinszky/katafygio

RUN apk --no-cache add git openssh-client ca-certificates

COPY katafygio /usr/local/bin/

USER 65534

CMD ["/usr/local/bin/katafygio"]
